### PR TITLE
organize upload system

### PR DESCRIPTION
**Pull request by bloxxite**
So this might break if you don't do this right.
This update organizes the upload system and names the files based on hash.

**! MOVE ALL OF YOUR FILES FOLDERS INTO THE RESPECTIVE FOLDER IN USERGENERATED !**

keep in mind this doesn't include pfps yet.

### CODE REVIEW

**Comment by ezist** [comment]
No

**Comment by bloxxite** [comment]
bruh what

**Comment by ezist** [comment]
Before you say I didn't even look over it, I saw these commits as they were being done on your repo a while ago. Try again.

**Comment by bloxxite** [comment]
what are you talking about lmao
i don't even know why you closed the pr

**Comment by ezist** [comment]
I'll let Typical decide on this, but I personally don't like it.

**Comment by bloxxite** [comment]
why not? you like files clogging up the root? or you don't like moving the existing folders?

**Comment by ezist** [comment]
It's fine for right now, but we should organize it sometime.

**Comment by typicalname0** [comment]
i might merge, but this changes a bit too much things. ill look into it later

**Comment by typicalname0** [comment]
there's conflicts, solve them

**Comment by bloxxite** [comment]
@typicalname0 this pr is getting stale. we're reaching the point of no return. I strongly advise suspending all development, and organizing things.

**Comment by typicalname0** [comment]
alright, i'll suspend development and wait for a day or so.

**Comment by typicalname0** [comment]
lots of conflicts

**Comment by ezist** [comment]
Pro-tip for the future: if you need to start over, make a new pull request instead of making a commit that deletes everything.

**Comment by ezist** [comment]
Closed in agreement with bloxxite,  he's going to make a new fork since the commit history for this PR is too unwieldy, and it'll be easier on him.

**Pull request closed without merging**
